build docker db
francoisbaudouin/LaZone pull request #17
Opened 2023-01-22 15:23 UTC by francoisbaudouin

2023-01-22 15:27 UTC, UgoBoulestreau approved these changes, later dismissed

2023-01-22 15:40 UTC, Kubirt requested changes

2023-01-22 15:40 UTC, Kubirt commented on server/dockerfile
> +RUN yarn add cors express mysql
replace with this "RUN yarn add cors express mysql express-session bcryptjs passport passport-local passport-jwt jsonwebtoken prisma @prisma/client dotenv nodemon"

2023-01-23 16:36 UTC, UgoBoulestreau approved these changes

2023-01-23 16:37 UTC, Kubirt approved these changes

2023-01-23 16:38 UTC, merged