Organise docker secret
francoisbaudouin/LaZone pull request #37
Opened 2023-02-06 11:48 UTC by francoisbaudouin

Now secret is hidden and you need to generete your own secrets_db.txt

2023-02-06 17:08 UTC, Kubirt requested changes

2023-02-06 17:08 UTC, Kubirt commented on flutter_application/pubspec.lock
> +# Generated by pub
il faut supprimer le fichier

2023-02-06 17:08 UTC, Kubirt commented on server/package-lock.json
> +{
il faut supprimer le fichier

2023-02-06 17:08 UTC, Kubirt commented on server/yarn.lock
il faut supprimer le fichier

2023-02-07 18:09 UTC, Kubirt submitted a review, later dismissed

2023-02-07 18:10 UTC, Kubirt submitted a review, later dismissed

2023-02-07 18:14 UTC, UgoBoulestreau submitted a review, later dismissed

2023-02-07 18:15 UTC, julienlafargue approved these changes, later dismissed

2023-02-08 12:51 UTC, julienlafargue submitted a review, later dismissed

2023-02-27 14:46 UTC, Kubirt approved these changes

2023-02-27 14:52 UTC, UgoBoulestreau approved these changes

2023-02-27 14:54 UTC, merged